#environment settings
export PATH=$PATH:$HOME/bin
export EDITOR=emacsclient
export LANG=jp_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export KCODE=u
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
