# alias
alias a='cd ..'
alias l='ls'
alias ls='ls -hFN --color=auto'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -Al'
alias lv='lv -Ou8'
alias diff='colordiff -u'
alias -g G='|grep --color=auto'
alias -g L='|lv -c'
