[aws]
symbol = "  "

[cmd_duration]
disabled  = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
style = "bold blue"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[@$hostname]($style) in "

[java]
symbol = " "

[julia]
symbol = " "

[localip]
disabled = true

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[username]
format = "[$user]($style)"
style_user = "bold dimmed green"
